### ISSUE TITLE
Can’t build...

### ISSUE THREAD

**Issue by PatchworkBoy** [KhaosT/HesperusBridgeConfigurator#1]
Fails to build for me...

> /Users/Marci/Downloads/HesperusBridgeConfigurator-master/HesperusBridgeConfigurator/BridgeSetupSession.swift:52:13:
> All stored properties of a class instance must be initialized before returning nil from an initialiser

Thrown at return nil:

> init?(service: HMService) {
>        if service.serviceType != BridgeConfigurationServiceDef.ServiceUUID {
>           return nil
>        }

**Comment by KhaosT** [comment]
What's the Xcode version you're using? Please make sure you try to build this project with latest Xcode (7.2.1)

**Comment by PatchworkBoy** [comment]
Yup - am using 7.2.1 (7C1002)

**Comment by KhaosT** [comment]
@PatchworkBoy oops, I'm using Swift 2.2 (with Xcode 7.3) and it appears in Swift 2.1, the class initializer cannot return nil unless it assign some value to the properties (which doesn't make any sense 😂 and they actually fixed this in Swift 2.2). Commit b5daeb1e3a296192f520c4773cacca45f121f599 should fix this.

**Comment by PatchworkBoy** [comment]
Ta!

**Comment by PatchworkBoy** [comment]
Confirmed https://github.com/KhaosT/HesperusBridgeConfigurator/commit/b5daeb1e3a296192f520c4773cacca45f121f599 fixes for use with xCode 7.2.1. Cheers!
